#!/usr/bin/env bash

# Trap signals
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Save PID to file
echo $$ > /var/run/myscript.pid

# Display messages indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
