#!/usr/bin/env bash
# kill infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
PID=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# If the process is running, kill it
if [ -n "$PID" ]; then
    kill -15 "$PID"
fi
