#!/usr/bin/env bash

# Trap SIGTERM signal
# Display 'To infinity and beyond' indefinitely in 2 seconds.

trap 'echo "I am invincible!!!"; exit' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
