#!/usr/bin/env bash

# Find the PID of the 7-highlander process
PID=$(pgrep "bash ./7-highlander" -f)

# If the process is running, kill it
if [ -n "$PID" ]; then
    kill -15 "$PID"
else
    echo "Process not found"
fi
