#!/usr/bin/env bash
# This script configures an Ubuntu server
# to resolve localhost to 127.0.0.2
# and facebook.com to 8.8.8.8.

# Update /etc/hosts file to set localhost
#to 127.0.0.2 and facebook.com to 8.8.8.8

sudo sed -i \
  's/^127\.0\.0\.1[[:space:]]localhost/127.0.0.1 localhost\n127.0.0.2 localhost/g' \
  /etc/hosts

sudo sed -i \
  's/^127\.0\.0\.1[[:space:]]facebook\.com/8.8.8.8 facebook.com/g' \
  /etc/hosts
echo "Changes applied. localhost now resolves to 127.0.0.2 and facebook.com to 8.8.8.8."
