#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine
# Get all active IPv4 IPs using ifconfig and filter out loopback addresses
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}' | grep -v '127.0.0.1'
